name: CI nodejs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup_nodejs_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update npm
        run: npm install -g npm@10.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: docker compose up -d
      - run: npm run test

