name: CI nodejs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup_nodejs_and_test:
    runs-on: ubuntu-22.04
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
      - name: Update npm
        run: npm install -g npm@10.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: docker image build -t nodejs_image ./
      - run: docker run nodejs_image npm run test
      - name: deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            whoami
            ls -al
