name: CI nodejs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  setup_nodejs_and_test:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Update npm
        run: npm install -g npm@10.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: docker image build -t nodejs_image ./
      - run: docker run nodejs_image npm run test
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            cd /usr
            rm -r blogCms
            docker kill $(docker ps -q)
            docker rm $(docker ps -aq)
            docker image rm nodejs_image
            git clone https://Yaamto:${{secrets.TOKEN_GIT}}@github.com/Yaamto/blogCms.git
            cd blogCms
            docker image build -t nodejs_image ./
            docker run -d -p 3000:3000 nodejs_image
